--- # AP Evergreen DEV DB Server setup
- hosts: db_server
  become: yes
  become_user: root
  connection: ssh
  gather_facts: yes
  vars:
    backup_bucket_name: apeg-prod-data-dumps
    backup_date: 2019-04-15
  roles:
    - role: mongo-db
      vars:
        mongodb_db_name: accounts
        mongodb_conf_name: accounts-mongo.conf
        mongodb_dbpath: /data/accounts-mongo
        mongodb_logpath: /var/log/accounts-mongo
        mongodb_pidFilePath: /var/run/accounts-mongo
        mongodb_port: 45601
        mongodb_admin_user: admin
        mongodb_admin_password: adminpass
        mongodb_user_name: apeguser
        mongodb_user_password: apegpass

    - role: mongo-db
      vars:
        mongodb_db_name: order-history
        mongodb_conf_name: order-history-mongo.conf
        mongodb_dbpath: /data/order-history-mongo
        mongodb_logpath: /var/log/order-history-mongo
        mongodb_pidFilePath: /var/run/order-history-mongo
        mongodb_port: 45602
        mongodb_admin_user: admin
        mongodb_admin_password: adminpass
        mongodb_user_name: apeguser
        mongodb_user_password: apegpass

    - role: mysql-db
      vars:
        mysqldb_name: balance
        mysqldb_port: 35600
        mysqldb_data_dir: /data/balance-mysql
        mysqldb_root_password: rootpass
        mysqldb_user_name: apeguser
        mysqldb_user_password: apegpass

    - role: mysql-db
      vars:
        mysqldb_name: reporting
        mysqldb_port: 35700
        mysqldb_data_dir: /data/reporting-mysql
        mysqldb_root_password: rootpass
        mysqldb_user_name: apeguser
        mysqldb_user_password: apegpass

