--- # AP Evergreen DEV DB Server setup
- hosts: db_server
  become: yes
  become_user: root
  connection: ssh
  gather_facts: yes
  roles:
    - role: mongo-db
      vars:
        backup_date: 2019-04-16
        mongodb_name: accounts
        mongodb_conf_name: accounts-mongo.conf
        mongodb_dbpath: /data/accounts-mongo
        mongodb_logpath: /var/log/accounts-mongo
        mongodb_pidFilePath: /var/run/accounts-mongo
        mongodb_port: 45601
        mongodb_admin_user: admin
        mongodb_admin_password: adminpass
        mongodb_db_name: accounts
        mongodb_user_name: apeguser
        mongodb_user_password: apegpass

    - role: mongo-db
      vars:
        backup_date: 2019-04-16
        mongodb_name: order-history
        mongodb_conf_name: order-history-mongo.conf
        mongodb_dbpath: /data/order-history-mongo
        mongodb_logpath: /var/log/order-history-mongo
        mongodb_pidFilePath: /var/run/order-history-mongo
        mongodb_port: 45602
        mongodb_admin_user: admin
        mongodb_admin_password: adminpass
        mongodb_db_name: orderHistory
        mongodb_user_name: apeguser
        mongodb_user_password: apegpass

    - role: mysql-db
      vars:
        backup_date: 2019-04-16
        mysqldb_name: balance
        mysql_port: 35600
        mysql_data_dir: /data/balance-mysql
        mysql_root_password: cosspass
        mysql_db_name: cossbalancedb
        mysql_user_name: cossbalance
        mysql_user_password: cosspass
#  - k-db-mongo
#  - e-db-mongo
#  - e-db-mongo-tracking
#  - internal-data
#  - redis
#  - mysql
